### ISSUE TITLE
SpiderOak has 2FA

### ISSUE THREAD

**Issue by almafeta** [2factorauth/twofactorauth#1045]
#211 reported SpiderOak had disabled 2FA permanently, but that was only a temporary bug with the SMS service, not a permanent shutdown.  backup.yml should be updated to the following:

```
  - name: SpiderOak
    url: https://spideroak.com/
    twitter: spideroak
    img: spideroak.png
    tfa: Yes
    sms: Yes
    exceptions:
        text: "US and Canada only.  Not available for free accounts."
    doc: https://blog.spideroak.com/20110620235134-2-factor-authentication-to-your-spideroak-account
```

I don't know where the token request URL https://spideroak.com/tokenrequest should go in this project's format.
