### ISSUE TITLE
Creating an optional popup for software checkmark

### ISSUE THREAD

**Issue by stephengroat** [2factorauth/twofactorauth#2067]
Looking at #2061, #2060, and #2057, it seems like if a specific software app is required, making the software checkmark popup a link to it would be a good idea (similar to the current exception system). It should probably be optional and need to have a list of the links to all of the different OS implementation (Android, iOS, etc.).

I'm envisioning the `_data` file looking like this:

```
  - name: Apple iCloud
    url: https://www.icloud.com
    img: icloud.png
    tfa: Yes
    sms: Yes
    software: Yes
      text: "iOS: www.apple.com"
    exceptions:
        text: "See http://support.apple.com/kb/HT5593 for a list of supported SMS carriers."
    doc: http://support.apple.com/kb/ht5570
```

and the website looking like it current

@psgs, any way you could help with this? I tried, but turned everything into spaghetti. I'm particularly having a hard time understanding what the `data.json` file does
