### ISSUE TITLE
Mail.Ru has broken docs link

### ISSUE THREAD

**Issue by conorgil** [2factorauth/twofactorauth#3108]
From Travis error log [here](https://travis-ci.org/2factorauth/twofactorauth/jobs/361973107)

In email.yml:
```yaml
    - name: Mail.Ru
      url: https://mail.ru/
      img: mailru.png
      tfa: Yes
      sms: Yes
      software: Yes
      doc: https://help.mail.ru/enmail-help/settings/2auth <----- THIS 404s
```
