### ISSUE TITLE
CM Telecom has broken docs link

### ISSUE THREAD

**Issue by conorgil** [2factorauth/twofactorauth#3109]
From Travis error log [here](https://travis-ci.org/2factorauth/twofactorauth/jobs/361973107)

In developer.yml:
```yaml
    - name: CM Telecom
      url: https://www.cmtelecom.com/
      img: cmtelecom.png
      tfa: Yes
      sms: Yes
      phone: Yes
      software: Yes
      doc: https://help.onlinesmsgateway.com/en/accounts-and-payments/how-do-i-enable-two-factor-authentication .  <---- THIS 404s AND I HAVE NO IDEA WHERE IT SHOULD ACTUALLY POINT
```

related to #3103
