### ISSUE TITLE
Softlayer has broken docs link

### ISSUE THREAD

**Issue by conorgil** [2factorauth/twofactorauth#3110]
From Travis error log [here](https://travis-ci.org/2factorauth/twofactorauth/jobs/361973107)

In hosting.yml:
```yaml
    - name: Softlayer
      url: https://www.softlayer.com
      img: softlayer.png
      tfa: Yes
      software: Yes
      doc: https://knowledgelayer.softlayer.com/procedure/configure-portal-account-one-time-password-access-manage . <---- THIS 403s
```

relates to #3103
