### ISSUE TITLE
Payza links are broken

### ISSUE THREAD

**Issue by conorgil** [2factorauth/twofactorauth#3112]
From Travis error log [here](https://travis-ci.org/2factorauth/twofactorauth/jobs/361973107)

In payments.yml:
```yaml
    - name: Payza
      url: https://www.payza.com/
      img: payza.png
      tfa: Yes
      software: Yes
      doc: https://docs.payza.com/docs/personal-manual-advanced-security#section-how-do-i-set-up-2-factor-authentication
```

Both links timeout.

Related to #3103
