### ISSUE TITLE
Rackspace docs link is broken

### ISSUE THREAD

**Issue by conorgil** [2factorauth/twofactorauth#3113]
From Travis error log [here](https://travis-ci.org/2factorauth/twofactorauth/jobs/361973107)

In hosting.yml:
```yaml
    - name: Rackspace
      url: https://www.rackspace.com/
      img: rackspace.png
      tfa: Yes
      sms: Yes
      doc: https://www.rackspace.com/knowledge_center/article/myrackspace-two-factor-authentication
```

Docs link 404s.

Related to #3103
