### ISSUE TITLE
Please add BT / British Telecom

### ISSUE THREAD

**Issue by dylmye** [2factorauth/twofactorauth#3744]
[Alexa rank #1,512](https://www.alexa.com/siteinfo/bt.com) - BT is the former state telecoms company and has the most broadband customers in the UK (unfortuante for them).

MFA status: "working" on a solution for the past 2 or so years. See [Community Forum mod response](https://community.bt.com/t5/Email/Still-no-2FA-on-BT-Email-accounts-in-2017/m-p/1913978/highlight/true#M66665).

This applies to both the [British Telecom portal](https://www.bt.com/mybt) and their white label of yahoo mail, [BT Mail](https://www.bt.com/mail) (though standard yahoo mail has 2fa).

Hope I've provided enough information. Thank you!

**Comment by dylmye** [comment]
Apologies, just seen the format in the contributing guidelines:
```YAML
websites:
  - name: BT British Telecom
    url: https://www.bt.com/
    img: ![bt_logo](https://user-images.githubusercontent.com/7024578/53166040-244ae780-35cc-11e9-9041-eb0b9c24f870.png)
    tfa: No
    status: https://community.bt.com/t5/Email/Still-no-2FA-on-BT-Email-accounts-in-2017/m-p/1913978/highlight/true#M66665
    twitter: bt_uk
    facebook: BTUK
    email: gavin.e.patterson@bt.com
```
With email, this is a public email contact that reaches the office of the CEO (can personally confirm)
