### ISSUE TITLE
API V2

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#4015]
I'm in the works of making a [new version](https://github.com/Carlgo11/twofactorauth/tree/tfa_tag) of the API and YAML layout.
In the new layout I've moved all tfa method tags into an array. I'm also in the process of creating a couple new tfa methods such as `U2F` and `TOTP` (RFC-6238).

My question is, what other tags should we list?

Should maybe WebAuthn be listed? If so, should it automatically list the site as supporting U2F as well?

Here is the WIP YAML layout:
```YAML
websites:
  - name: Site Name
    url: https://example.com
    img: example.png
    tfa:
      - sms
      - phone
      - email
      - software (for legacy support)*
      - totp (RFC-6238 2FA)*
      - proprietary (non-RFC-6238 software 2FA)*
      - hardware
      - u2f
    doc: https://example.com/2fa
```
__*__ _everything inside `()` is a comment and not part of the YAML layout_

Here's the WIP JSON layout:
```JSON
{
  "Example Category": {
    "Site Name": {
      "url": "https://example.com",
      "img": "example.png",
      "tfa": [
        "sms",
        "phone",
        "email",
        "software",
        "totp",
        "proprietary",
        "u2f"
      ],
      "doc": "https://example.com/2fa"
    }
}
```

I would love some feedback on the tfa methods as well as the JSON layout!
