### ISSUE TITLE
Add Galaxus

### ISSUE THREAD

**Issue by winkler-winsen** [2factorauth/twofactorauth#4987]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `Galaxus`

* Site URL - `https://www.galaxus.de/` `https://www.galaxus.ch/` `https://www.galaxus.at/` (coming soon)

* Does the site support 2FA? - `Yes`

* Documentation URL - `https://www.galaxus.de/de/CustomerAccount/TwoFactAuth#TwoFactAuthControl`

### Information about what methods of 2FA the site supports: ###

* Software:
  - [x] TOTP (RFC-6238, Google Authenticator)
  - [ ] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

**Comment by winkler-winsen** [comment]
_data\retail.yml 
```
 - name: Galaxus (DE)
    url: https://www.galaxus.de/
	img: galaxus.png
	tfa:
	  - totp
	twitter: Galaxus_de
	facebook: galaxusDE
	lang: de
	doc: https://www.galaxus.de/de/CustomerAccount/TwoFactAuth#TwoFactAuthControl

  - name: Galaxus (CH)
    url: https://www.galaxus.ch/
	img: galaxus.png
	tfa:
	  - totp
	twitter: Galaxus
	facebook: galaxus
	lang: de
	doc: https://www.galaxus.de/ch/CustomerAccount/TwoFactAuth#TwoFactAuthControl

```
img\retail\glaxus.png 
![glaxus](https://user-images.githubusercontent.com/43114182/95002434-3ed0a980-05d4-11eb-90e9-ec9a1e1c425a.png)
