### ISSUE TITLE
International Domains for Amazon

### ISSUE THREAD

**Issue by OLLI-S** [2factorauth/twofactorauth#5072]
My password manager **Bitwarden** reports me entries, where 2FA is available but not set up.
For my Amazon account I get no warning that 2FA is missing.
The reason is that I live in Germany and here the local Amazon Domain is https://www.amazon.de/ (country domain **.de**)
In the Tow Factor Auth List the domain for Amazon is https://www.amazon.com/ (country domain **.com**)

So I suggest that you add all local Amazon URLs to the 2FA list.
Because it is essential to protect the Amazon account with 2FA and I know hat your service is used by many other password managers.

**Comment by phallobst** [comment]
Bitwarden uses the API files for these checks, I assume. In order to keep the number of entries in the categories to a minimum, I could imagine to include "alias" URLs in the YAML sources, but _not_ generate extra table entries for these in the given category (since they would not include relevant additional information anyway). But for the API files we could duplicate the information for each registered alias URL.

If the 2FA options for the corresponding TLDs are different, we should still create a separate entry of course (see Santander bank for example).

**Comment by OLLI-S** [comment]
I don't know how Bitwarden uses your data (I am a normal user).
But I will link this post in the Bitwarden forums, so the Bitwarden staff can have a look.

But when I create a new entry in Bitwarden and use the URL https://www.santander.de/
then Bitwarden lists this entry in the "Inactive 2FA report".
So it seems to work.

**Comment by phallobst** [comment]
I had a quick look:
https://github.com/bitwarden/web/blob/master/src/app/tools/inactive-two-factor-report.component.ts#L79
They load the v1 API data to check whether 2FA is available for a given URL.

**Comment by OLLI-S** [comment]
OK, so there is no more information from the Bitwarden staff needed?

**Comment by phallobst** [comment]
Yeah, I guess we're good.

**Comment by Carlgo11** [comment]
Just a quick note: Even if we implement something like a domain array for entries in our lists, it still won't show up on Bitwarden as long as they keep using API v1. That's a depricated version which won't get any new features.

**Comment by phallobst** [comment]
I actually meant to create the API files as if there were separate entries, i.e. something like
```yaml
name: Amazon
url: https://www.amazon.com
aliases:
  - DE: https://www.amazon.de
  - UK: https://www.amazon.co.uk
img: amazon.png
```
would create the same API files as
```yaml
name: Amazon
url: https://www.amazon.com
img: amazon.png

name: Amazon (DE)
url: https://www.amazon.de
img: amazon.png

name: Amazon (UK)
url: https://www.amazon.co.uk
img: amazon.png
```
(The syntax is just an example, of course. Maybe the names could even be the same, without any suffix.)

On the website, there would still be only one entry "Amazon", pointing at https://www.amazon.com - the aliases would simply be ignored there.

That means that the structure of the API files (v1 or v2) would not change at all, but only the way they are built.
