### ISSUE TITLE
Add column for TOTP

### ISSUE THREAD

**Issue by maltfield** [2factorauth/twofactorauth#5168]
- [X] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###

Can you please **add a column** to the table that denotes whether or not the service provides **support for TOTP**?

### See also

 * https://en.wikipedia.org/wiki/Time-based_One-Time_Password
 * https://en.wikipedia.org/wiki/Google_Authenticator
 * https://tools.ietf.org/html/rfc6238

**Popular Client-based Implementations**

 * [Google Authenticator](https://github.com/google/google-authenticator)
 * [andOTP](https://f-droid.org/en/packages/org.shadowice.flocke.andotp/)
 * [Authy](https://authy.com/download/)

**Comment by maltfield** [comment]
First, thank you for your work on this valuable website!

I think every other year I try to find a list of the "most secure banks" that will actually let me lock down my account to be at least as secure as, say, my github account. Each time, I spend a few hours searching, but always fail to find a bank that takes security seriously. And I always end-up finding my way to https://twofactorauth.org/

Unfortunately, the way most banks implement 2FA actually makes their account *less* secure (using insecure SMS to send the OTP, which their account reps may actually use as a backdoor *alternative* to the password = something-you-know factor :facepalm:)

If twofactorauth.org could list which banks support TOTP, it would be enormously helpful start to weed out the banks that use 2FA for *actual* security of their users vs those that do it just to check the box for auditors (security theater).

**Comment by maltfield** [comment]
TIL this data is already available, though it's not displayed on the WUI.

You can get a list of which banks support TOTP by the following commands (on Linux)

```
git clone https://github.com/2factorauth/twofactorauth.git
cd twofactorauth/_data/
grep -iB5 'totp' banking.yml
```

For example, today I can see that Addiko Bank, Avanza, Bitwala, and Woodforest National Bank all support TOTP:

```
user@disp5283:~$ git clone https://github.com/2factorauth/twofactorauth.git
Cloning into 'twofactorauth'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 31034 (delta 13), reused 27 (delta 9), pack-reused 30996
Receiving objects: 100% (31034/31034), 14.58 MiB | 2.90 MiB/s, done.
Resolving deltas: 100% (17733/17733), done.
user@disp5283:~$

user@disp5283:~$ cd twofactorauth/_data/
user@disp5283:~/twofactorauth/_data$ 

user@disp5283:~/twofactorauth/_data$ grep -iB5 'totp' banking.yml 

  - name: Addiko Bank
    url: https://www.addiko.hr/
    img: addikobank.png
    tfa:
      - totp
--

  - name: Avanza
    url: https://www.avanza.se/
    img: avanza.png
    tfa:
      - totp
--
  - name: Bitwala
    url: https://www.bitwala.com/
    img: bitwala.png
    tfa:
      - sms
      - totp
--

  - name: Woodforest National Bank
    url: https://www.woodforest.com/
    img: woodforest.png
    tfa:
      - totp
user@disp5283:~/twofactorauth/_data$ 
```
